const ADD_USER='ADD_USER'
const UPDATE_USER='UPDATE_USER'
const DELETE_USER='DELETE_USER'
const CHECKLOGIN_USER='CHECKLOGIN-USER'
const CHECKLOGOUT_USER='CHECKLOGOUT-USER'
const CHECKADDORUPDATE='CHECKADDORUPDATE'
const GET="GET"
export {ADD_USER,UPDATE_USER,DELETE_USER,CHECKLOGIN_USER,CHECKLOGOUT_USER,CHECKADDORUPDATE,GET}